### ISSUE TITLE
Create Add New Student page

### ISSUE THREAD

**Issue by AhmedShaaban11** [Hackers-of-The-Day-and-Night/Student-Affairs-Website#2]
# Tasks
- [x] Empty nav element (will be used later)
- [x] H1 with the name of the page
- [x] Input text: name
- [x] Input email: email
- [x] Input date: date of birth
- [x] Input Radio: gender
- [x] Input number: phone
- [x] Submit Button
- [x] Confirm popup
