### ISSUE TITLE
Create Edit/Delete page

### ISSUE THREAD

**Issue by AhmedShaaban11** [Hackers-of-The-Day-and-Night/Student-Affairs-Website#3]
# Tasks
- [ ] Empty nav element (will be used later)
- [ ] H1: Edit/Delete
- [ ] Input text Readonly: name
- [ ] Input email: email
- [ ] Input number Readonly: gpa
- [ ] Input number Readonly: level
- [ ] Input text Readonly: status
- [ ] Input text Readonly: department
- [ ] Input date: date of birth
- [ ] Input Radio: gender
- [ ] Input number: phone
- [ ] Save Button
- [ ] Confirm popup for save
- [ ] Delete Student Button
- [ ] Confirm popup for Delete
