### ISSUE TITLE
Create Search for Active page

### ISSUE THREAD

**Issue by AhmedShaaban11** [Hackers-of-The-Day-and-Night/Student-Affairs-Website#4]
# Tasks
- [x] Empty nav element (will be used later)
- [x] H1: Search for Active
- [x] Input search
- [x] Create initial result table
  - [x] Only one column having student names
  - [x] Each name is a link to assign_department page (If not made yet, type only '#')
