### ISSUE TITLE
Create Assign Department page

### ISSUE THREAD

**Issue by AhmedShaaban11** [Hackers-of-The-Day-and-Night/Student-Affairs-Website#5]
# Tasks
- [x] Empty nav element (will be used later)
- [x] H1: Assign Department
- If stud level = 3
    - [x] Input number readonly: stud id
    - [x] Dropdown with available departments
    - [x] Submit button
    - [x] Confirm popup
- Else
    - [x] Error msg with clear  understandable statement
