### ISSUE TITLE
Create View page

### ISSUE THREAD

**Issue by AhmedShaaban11** [Hackers-of-The-Day-and-Night/Student-Affairs-Website#6]
# Tasks
- [x] Empty nav element (will be used later)
- [x] H1: View Page
- [x] Input search for all
- Initial result table (make 5 rows) with
    - [x] Stud ids
    - [x] Stud names
    - [x] Stud emails
    - [x] Stud phones
    - [x] edit/delete link
    - [x] Toggle status button
