### ISSUE TITLE
Create nav script

### ISSUE THREAD

**Issue by AhmedShaaban11** [Hackers-of-The-Day-and-Night/Student-Affairs-Website#7]
# Description
This nav script should be included in each html page that has nav
This will make the nav standard in the whole project
# Tasks
- [x] Create nav.js
- [x] Implement the nav
- [x] Include nav.js in all required pages
